"""empty message

Revision ID: 327590ca955a
Revises: 5fd2bc33d23f
Create Date: 2021-12-15 02:19:55.076871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327590ca955a'
down_revision = '5fd2bc33d23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_data', sa.DATETIME(), nullable=False))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
