"""empty message

Revision ID: ea0cac843e28
Revises: fca66694d5a2
Create Date: 2021-12-18 04:29:04.735051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0cac843e28'
down_revision = 'fca66694d5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('modify_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_data', sa.DATETIME(), nullable=True))
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
